spring.vivid.rest.application-id-header-name = ${spring.vivid.application-id-header-name}
spring.vivid.rest.api-token-header-name = ${spring.vivid.api-token-header-name}

spring.vivid.sse.application-id-header-name = ${spring.vivid.application-id-header-name}
spring.vivid.sse.api-token-header-name = ${spring.vivid.api-token-header-name}
