spring.vivid.rest.application-id-header-name=X-Application-Id
spring.vivid.rest.api-token-header-name=X-Api-Token

spring.vivid.sse.application-id-header-name=${spring.vivid.rest.application-id-header-name}
spring.vivid.sse.api-token-header-name=${spring.vivid.rest.api-token-header-name}
spring.vivid.sse.base-url=${spring.vivid.rest.base-url}
spring.vivid.sse.api-key=${spring.vivid.rest.api-key}