spring.vivid.rest.header-names.application-name=X-Vivid-Application-Name
spring.vivid.rest.header-names.client-token=X-Vivid-Client-Token
spring.vivid.rest.header-names.environment=X-Vivid-Environment


spring.vivid.sse.header-names.application-name=${spring.vivid.rest.header-names.application-name}
spring.vivid.sse.header-names.client-token=${spring.vivid.rest.header-names.client-token}
spring.vivid.sse.header-names.environment=${spring.vivid.rest.header-names.environment}
spring.vivid.sse.base-url=${spring.vivid.rest.base-url}

spring.vivid.rest.heartbeat.enabled=true