spring:
  application:
    name: vivid-backend
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5333/vivid}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8989/realms/vivid
  flyway:
    baseline-version: 0
    baseline-description: Setup initial database
    baseline-on-migrate: true

server:
  port: 8080

vivid:
  auth:
    issuer: http://localhost:8989/realms/vivid
    client-id: vivid-client
    frontend-base-url: http://localhost:4200

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
